############################
## CHANGE THESE
############################

baseURL: "https://martindonat.github.io/afterwritingblog"
title: afterwritingblog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
